language: node_js
node_js:
- '8'
branchs:
  only:
  - master
install: true
script: true
after_success:
- chmod 600 ~/.ssh/id_rsa
- ssh root@39.106.211.6 -o StrictHostKeyChecking=no '/data/apps/front/git-travis/script/deploy.sh'
addons:
  ssh_known_hosts: 39.106.211.6


