language: node_js
node_js:
- '8'
branchs:
  only:
  - master
install: true
script: true
after_success:
- chmod 600 ~/.ssh/id_rsa
- ssh travis@39.106.211.6 -o StrictHostKeyChecking=no 'cd ~/git-travis && git pull'
addons:
  ssh_known_hosts: 39.106.211.6
before_install:
- openssl aes-256-cbc -K $encrypted_15222852af1b_key -iv $encrypted_15222852af1b_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
